name: Test ChatGPT Issue Commentator

on:
    issue_comment:
        types: [created]

jobs:
    run_chatgpt_issue_commentator:
        runs-on: ubuntu-latest
        steps:
        - name: Run ChatGPT Issue Commentator
          uses: igsr5/chatgpt-issue-commentator@master
          with:
              openai-api-key: ${{ secrets.OPENAI_API_KEY }}
              github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
